# Generated by Django 5.2.11 on 2026-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="field_of_study",
            field=models.CharField(
                choices=[
                    ("Civil Engineering", "Civil Engineering"),
                    ("Mechanical Engineering", "Mechanical Engineering"),
                    ("Electrical Engineering", "Electrical Engineering"),
                    ("Electronics Engineering", "Electronics Engineering"),
                    ("Computer Engineering", "Computer Engineering"),
                ],
                default="Civil Engineering",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="is_mobile_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="MobileOTP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mobile_number", models.CharField(max_length=20)),
                ("otp_code", models.CharField(max_length=6)),
                ("purpose", models.CharField(choices=[("register", "Register"), ("login", "Login")], default="register", max_length=20)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mobileotp",
            index=models.Index(fields=["mobile_number", "purpose"], name="accounts_mo_mobile__747906_idx"),
        ),
        migrations.AddIndex(
            model_name="mobileotp",
            index=models.Index(fields=["expires_at"], name="accounts_mo_expires_7c606a_idx"),
        ),
    ]
