# Generated by Django 5.2.11 on 2026-03-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_profile_fields_and_mobileotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MobileOTP",
        ),
    ]
