# Generated by Django 4.2 on 2026-05-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_referral_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralinvite',
            new_name='accounts_re_friend__7969d4_idx',
            old_name='accounts_ref_friend_mobile_norm',
        ),
        migrations.RenameIndex(
            model_name='referralinvite',
            new_name='accounts_re_friend__3846e8_idx',
            old_name='accounts_ref_friend_name_norm',
        ),
    ]
