# Generated by Django 5.2.11 on 2026-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dropbox_path', models.CharField(max_length=1000, unique=True)),
                ('content_type', models.CharField(choices=[('notice', 'Notice'), ('syllabus', 'Syllabus'), ('old_question', 'Old Question'), ('subjective', 'Subjective')], max_length=20)),
                ('branch', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('branch',)},
            },
        ),
    ]
