# Generated by Django 5.2.11 on 2026-02-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemetadata",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("notice", "Notice"),
                    ("syllabus", "Syllabus"),
                    ("old_question", "Old Question"),
                    ("subjective", "Subjective"),
                    ("take_exam_mcq", "Take Exam MCQ"),
                    ("take_exam_subjective", "Take Exam Subjective"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlatformMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrolled_students", models.PositiveIntegerField(blank=True, null=True)),
                ("objective_mcqs_available", models.PositiveIntegerField(blank=True, null=True)),
                ("resource_files_available", models.PositiveIntegerField(blank=True, null=True)),
                ("exam_sets_available", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
