# Generated by Django 5.2.11 on 2026-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_platformmetrics_alter_filemetadata_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformmetrics",
            name="motivational_image_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="platformmetrics",
            name="motivational_quote",
            field=models.TextField(blank=True, default=""),
        ),
    ]
