# Generated by Django 4.2 on 2026-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_filemetadata_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dropbox_path', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('content_type', models.CharField(choices=[('notice', 'Notice'), ('syllabus', 'Syllabus'), ('old_question', 'Old Question'), ('subjective', 'Subjective'), ('objective_mcq', 'Objective MCQ'), ('take_exam_mcq', 'Take Exam MCQ'), ('take_exam_subjective', 'Take Exam Subjective')], max_length=20)),
                ('branch', models.CharField(max_length=200)),
                ('parent_path', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['branch', 'content_type', 'depth', 'sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='content_type',
            field=models.CharField(choices=[('notice', 'Notice'), ('syllabus', 'Syllabus'), ('old_question', 'Old Question'), ('subjective', 'Subjective'), ('objective_mcq', 'Objective MCQ'), ('take_exam_mcq', 'Take Exam MCQ'), ('take_exam_subjective', 'Take Exam Subjective')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='foldermetadata',
            index=models.Index(fields=['branch', 'content_type', 'is_visible'], name='storage_fol_branch_fdd6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='foldermetadata',
            index=models.Index(fields=['branch', 'content_type', 'parent_path', 'sort_order'], name='storage_fol_branch_0e91bd_idx'),
        ),
    ]
