# Generated by Django 4.2 on 2026-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_foldermetadata_alter_filemetadata_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='foldermetadata',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='foldermetadata',
            name='icon_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='platformmetrics',
            name='login_hero_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='platformmetrics',
            name='register_hero_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='foldermetadata',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
