# Generated by Django 5.2.11 on 2026-02-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_chapter_mcqquestion_subject_chapter_subject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examattempt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="exampurchase",
            options={"ordering": ["-purchased_at"]},
        ),
        migrations.AlterModelOptions(
            name="subjectivesubmission",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AddField(
            model_name="examattempt",
            name="answers_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="correct_answers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="total_questions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="unanswered",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="wrong_answers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exampurchase",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="exampurchase",
            name="payment_gateway",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="exampurchase",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="mcqquestion",
            name="question_header",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mcqquestion",
            name="question_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="answer_pdf",
            field=models.FileField(blank=True, null=True, upload_to="subjective_submissions/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending Review"), ("reviewed", "Reviewed"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subjectivesubmission",
            name="file_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="ExamSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("branch", models.CharField(default="Civil Engineering", max_length=200)),
                (
                    "exam_type",
                    models.CharField(choices=[("mcq", "Multiple Choice"), ("subjective", "Subjective")], max_length=20),
                ),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("is_free", models.BooleanField(default=True)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("duration_seconds", models.PositiveIntegerField(default=1800)),
                ("grace_seconds", models.PositiveIntegerField(default=60)),
                ("negative_marking", models.DecimalField(decimal_places=2, default=0.25, max_digits=4)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "branch", "exam_type")},
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=1)),
                ("question_header", models.CharField(blank=True, max_length=255)),
                ("question_text", models.TextField()),
                ("question_image_url", models.URLField(blank=True)),
                ("option_a", models.CharField(blank=True, max_length=500)),
                ("option_b", models.CharField(blank=True, max_length=500)),
                ("option_c", models.CharField(blank=True, max_length=500)),
                ("option_d", models.CharField(blank=True, max_length=500)),
                (
                    "correct_option",
                    models.CharField(blank=True, choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")], max_length=1, null=True),
                ),
                ("explanation", models.TextField(blank=True)),
                ("marks", models.PositiveIntegerField(default=1)),
                (
                    "exam_set",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="exams.examset"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examattempt",
            name="exam_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="exams.examset",
            ),
        ),
        migrations.AddField(
            model_name="exampurchase",
            name="exam_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="exams.examset",
            ),
        ),
        migrations.AddField(
            model_name="subjectivesubmission",
            name="exam_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjective_submissions",
                to="exams.examset",
            ),
        ),
    ]
