# Generated by Django 5.2.11 on 2026-03-07 17:20

from django.db import migrations, models


def seed_institution_folders(apps, schema_editor):
    Subject = apps.get_model("exams", "Subject")
    ExamSet = apps.get_model("exams", "ExamSet")
    InstitutionFolder = apps.get_model("exams", "InstitutionFolder")

    from exams.path_utils import GENERAL_INSTITUTION, parse_exam_source_path, parse_subject_key

    seen = set()

    def upsert(branch, scope, folder_key, display_name):
        key = str(folder_key or "").strip() or GENERAL_INSTITUTION
        label = str(display_name or "").strip() or key
        dedupe = (branch, scope, key)
        if dedupe in seen:
            return
        seen.add(dedupe)

        obj, created = InstitutionFolder.objects.get_or_create(
            branch=branch,
            scope=scope,
            folder_key=key,
            defaults={"display_name": label},
        )
        if not created and not obj.display_name:
            obj.display_name = label
            obj.save(update_fields=["display_name", "updated_at"])

    for subject in Subject.objects.values("branch", "name"):
        meta = parse_subject_key(subject.get("name", ""))
        upsert(
            branch=subject.get("branch") or "Civil Engineering",
            scope="objective",
            folder_key=meta.get("institution_key") or GENERAL_INSTITUTION,
            display_name=meta.get("institution_display") or GENERAL_INSTITUTION,
        )

    for exam_set in ExamSet.objects.values("branch", "exam_type", "source_file_path"):
        exam_type = exam_set.get("exam_type") or "mcq"
        scope = "take_exam_subjective" if exam_type == "subjective" else "take_exam_mcq"
        source_path = str(exam_set.get("source_file_path") or "")
        if source_path.lower().startswith("/bridge4er/"):
            meta = parse_exam_source_path(
                source_file_path=source_path,
                branch=exam_set.get("branch") or "Civil Engineering",
                exam_type=exam_type,
            )
            institution = meta.get("institution") or GENERAL_INSTITUTION
        else:
            institution = GENERAL_INSTITUTION
        upsert(
            branch=exam_set.get("branch") or "Civil Engineering",
            scope=scope,
            folder_key=institution,
            display_name=institution,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_chapter_small_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examset",
            options={"ordering": ["display_order", "name", "id"], "unique_together": {("name", "branch", "exam_type")}},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["display_order", "name", "id"], "unique_together": {("name", "branch")}},
        ),
        migrations.AddField(
            model_name="examset",
            name="display_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="subject",
            name="display_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="InstitutionFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("branch", models.CharField(max_length=200)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("objective", "Objective MCQ"),
                            ("take_exam_mcq", "Take Exam - MCQ"),
                            ("take_exam_subjective", "Take Exam - Subjective"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("folder_key", models.CharField(db_index=True, max_length=255)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scope", "branch", "display_order", "folder_key", "id"],
                "unique_together": {("branch", "scope", "folder_key")},
            },
        ),
        migrations.RunPython(seed_institution_folders, noop_reverse),
    ]
