# Generated by Django 4.2 on 2026-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_subject_display_order_examset_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='total_marks_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectivesubmission',
            name='reviewed_file',
            field=models.FileField(blank=True, null=True, upload_to='subjective_reviews/%Y/%m/%d/'),
        ),
    ]
