# Generated by Django 4.2.0 on 2026-02-18 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0004_alter_examattempt_options_alter_exampurchase_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("gateway", models.CharField(choices=[("esewa", "eSewa"), ("khalti", "Khalti")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile_number", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("gateway_reference", models.CharField(blank=True, max_length=255)),
                ("gateway_transaction_id", models.CharField(blank=True, max_length=255)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="exams.examset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["gateway", "status"], name="payments_pa_gateway_186290_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["gateway_reference"], name="payments_pa_gateway_3df281_idx"),
        ),
    ]
